accounts/urls.py
from django.urls import path

from .views import SignUpView


urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

blog/urls.py
from django.urls import path

from .views import (
    BlogListView,
    BlogDetailView,
    BlogCreateView,
    BlogUpdateView,
    BlogDeleteView,
)

urlpatterns = [
    path("", BlogListView.as_view(), name="home"),
    path("post/<int:pk>/", BlogDetailView.as_view(), name="post_detail"),
    path("post/new/", BlogCreateView.as_view(), name="post_new"),
    path("post/<int:pk>/edit/", BlogUpdateView.as_view(), name="post_edit"),
    path("post/<int:pk>/delete/", BlogDeleteView.as_view(), name="post_delete"),
]

blogin/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
]

accounts/models.py
from django.db import models

blog/models.py
from django.db import models
from django.urls import reverse


class Post(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(
        "auth.User",
        on_delete=models.CASCADE,
    )
    body = models.TextField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            "post_detail",
            kwargs={"pk": self.pk},
        )

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView


class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

blog/views.py
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)

from .models import Post


class BlogListView(ListView):
    model = Post
    template_name = "pages/home.html"


class BlogDetailView(DetailView):
    model = Post
    template_name = "pages/detail.html"


class BlogCreateView(CreateView):
    model = Post
    template_name = "pages/post_create.html"
    fields = ["title", "author", "body"]


class BlogUpdateView(UpdateView):
    model = Post
    template_name = "pages/post_edit.html"
    fields = ["title", "body"]


class BlogDeleteView(DeleteView):
    model = Post
    template_name = "pages/post_delete.html"
    success_url = reverse_lazy("home")

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="description"
          content="Blogin is an open source blogging app written with python framework django"/>
    <meta name="keywords" content="Blog"/>
    <link rel="shortcut icon"
          href="{% static 'img/favicon.png' %}"
          type="image/x-icon"/>
    <link rel="stylesheet" href="{% static 'fonts/Inter/inter.css' %}"/>
    <link rel="stylesheet" href="{% static 'bootstrap/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    {% block head %}
    {% endblock head %}
    <title>Blogin
      {% block title %}
      {% endblock title %}
    </title>
  </head>
  <body class="bg-light min-vh-100 d-flex flex-column h-100">
    {% comment %} Navbar {% endcomment %}
    {% include "navbar.html" %}
    {% comment %} Main content {% endcomment %}
    <main role="main" class="flex-shrink-0">
      <div class="container">
        {% block content %}
        {% endblock content %}
      </div>
    </main>
    {% comment %} Footer {% endcomment %}
    {% include "footer.html" %}
    <script src="{% static 'jquery/jquery-3.5.1.slim.min.js' %}"></script>
    <script src="{% static 'bootstrap/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
  </body>
</html>

templates/footer.html
{% load static %}
<footer class="footer mt-auto py-3">
  <div class="container d-flex justify-content-between">
    <span class="text-muted">&copy; Dayal Moirangthem, 2022</span>
    <span class="text-muted align-center">powered by
      <img src="{% static 'img/favicon.png' %}"
           height="20px"
           width="20px"
           alt=""/>
    </span>
  </div>
</footer>

templates/modals.html
<div class="modal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Modal title</h5>
        <button type="button"
                class="btn-close"
                data-bs-dismiss="modal"
                aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>Modal body text goes here.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

templates/navbar.html
{% load static %}
{% comment %} <header class=" nav-tabs" style="background-color: #e3f2fd;">
  <!-- Fixed navbar -->
  <nav class="navbar navbar-expand-md navbar-light container">
    <a class="navbar-brand" href="{% url 'home' %}">Bloggin</a>
    <div>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="#">Link</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
    </div>
    <div class="navbar-nav ml-auto d-flex align-items-center" style="gap: 10px">
      {% if user.is_authenticated %}
        <a class="nav-link" href="{% url 'post_new' %}">+ New Blog Post</a>
        <span class="align-self-center">{{ user.username }}</span>
        <span class="d-flex">
          <img src="{% static 'img/avatar.png' %}" height="32px" width="32px" alt="avatar" class="rounded-circle"/>
        </span>
      {% else %}
        <a href="{% url 'login' %}" class="nav-link">Log in</a>
      {% endif %}
    </div>
  </nav>
</header> {% endcomment %}
<header class="mb-4">
  <nav class="navbar navbar-expand-lg bg-primary navbar-dark">
    <div class="container d-flex flex-row">
      <a class="navbar-brand" href="{% url 'home' %}">Bloggin</a>
      <button class="navbar-toggler"
              type="button"
              data-bs-toggle="collapse"
              data-bs-target="#navbarNavDropdown"
              aria-controls="navbarNavDropdown"
              aria-expanded="false"
              aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item show">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item show">
            <a class="nav-link" href="#">Features</a>
          </li>
          <li class="nav-item show">
            <a class="nav-link" href="#">Pricing</a>
          </li>
          <li class="nav-item dropdown show">
            <a class="nav-link dropdown-toggle"
               href="#"
               role="button"
               data-bs-toggle="dropdown"
               aria-expanded="false">
              Dropdown link
            </a>
            <ul class="dropdown-menu">
              <li>
                <a class="dropdown-item" href="#">Action</a>
              </li>
              <li>
                <a class="dropdown-item" href="#">Another action</a>
              </li>
              <li>
                <a class="dropdown-item" href="#">Something else here</a>
              </li>
            </ul>
          </li>
        </ul>
      </div>
      <div class="btn-group navbar-nav ml-auto d-flex align-items-center align-self-end">
        {% if user.is_authenticated %}
          <a class="nav-link text-white" href="{% url 'post_new' %}">+ New Blog Post</a>
          <button class="avatar btn btn-tertiary border-0 d-flex flex-row dropdown-toggle align-items-center text-white fw-semibold"
                  type="button"
                  id="triggerId"
                  data-bs-toggle="dropdown"
                  aria-haspopup="true"
                  aria-expanded="false">
            <img src="{% static 'img/avatar.png' %}"
                 height="37px"
                 width="37px"
                 alt="avatar"
                 class="rounded-circle mx-2 border border-4 border-white border-opacity-25"/>
          </button>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="triggerId">
            <span class="d-flex align-items-center justify-content-center mt-4">
              <img src="{% static 'img/avatar.png' %}"
                   height="37px"
                   width="37px"
                   alt="avatar"
                   class="rounded-circle mx-2 border border-4 border-primary border-opacity-25"/>
            </span>
            <span class="dropdown-item-text text-center mb-3">{{ user.username }}</span>
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item disabled" href="#">Disabled action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
          </div>
        {% else %}
          <a class="nav-link text-white" href="{% url 'signup' %}">Sign up</a>
          <a class="nav-link text-white" href="{% url 'login' %}">Log in</a>
        {% endif %}
      </div>
    </div>
  </nav>
</header>

templates/pages/detail.html
{% extends "base.html" %}
{% block title %}
  Detail
{% endblock title %}
{% block content %}
  <div class="post-detail">
    <h2>{{ post.title }}</h2>
    <p class="text-dark">Written by: {{ post.author }}</p>
    <p>{{ post.body }}</p>
  </div>
  <div class="d-flex p-1" style="gap:10px">
    <a class="btn btn-primary mr-2" href="{% url 'post_edit' post.pk %}">Edit</a>
    <a class="btn btn-danger" href="{% url 'post_delete' post.pk %}">Delete</a>
  </div>
{% endblock content %}

templates/pages/home.html
{% extends "base.html" %}
{% block title %}
  Home
{% endblock title %}
{% block content %}
  {% for post in post_list %}
    <div class="post-entry my-4 card p-4">
      <h2>
        <a class="text-decoration-none" href="{{ post.get_absolute_url }}">{{ post.title }}</a>
      </h2>
      <p class="mb-0 text-muted font-italic">{{ post.author }}</p>
      <p class="mb-0">{{ post.body|truncatewords:20|linebreaks }}</p>
    </div>
  {% endfor %}
{% endblock content %}

templates/pages/post_create.html
{% extends "base.html" %}
{% block content %}
  <h1>New post</h1>
  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
  </form>
{% endblock content %}

templates/pages/post_delete.html
{% extends "base.html" %}
{% block content %}
  <h1>Delete post</h1>
  <form action="" method="post">
    {% csrf_token %}
    <p>Are you sure to delete {{ post.title }}?</p>
    <div class="d-flex justify-content-between">
      <a href="{% url 'post_detail' post.pk %}"
         class="btn btn-terriary table-bordered">Cancel</a>
      <input class="btn btn-danger" type="submit" value="Delete" />
    </div>
  </form>
{% endblock content %}

templates/pages/post_edit.html
{% extends "base.html" %}
{% block content %}
  <h1>Edit post</h1>
  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" />
  </form>
{% endblock content %}

templates/pagination.html
<nav aria-label="Page navigation">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link"
           href="?page={{ page_obj.previous_page_number }}"
           aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
          <span class="sr-only">Previous</span>
        </a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
          <span class="sr-only">Previous</span>
        </a>
      </li>
    {% endif %}
    <li class="page-item disabled">
      <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }} of {{ paginator.num_pages }}</a>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link"
           href="?page={{ page_obj.next_page_number }}"
           aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
          <span class="sr-only">Next</span>
        </a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
          <span class="sr-only">Next</span>
        </a>
      </li>
    {% endif %}
  </ul>
</nav>